import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const admin='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002';
test('財務DB：管理者限定・下書き隔離・競合拒否・公開撤回・非公開銘柄除外',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 grant usage on schema public,auth to anon,authenticated,service_role;`);
 for(const file of ['0001_init.sql','0002_comment_mfa_audit_notes.sql','0003_price_event_enums.sql','0004_inbox.sql','0007_tracking_articles.sql','0008_article_validation.sql'])await db.exec(fs.readFileSync(`supabase/migrations/${file}`,'utf8'));
 await db.exec(`insert into auth.users values('${admin}'),('${other}');insert into admin_users(user_id) values('${admin}');insert into companies(security_code,name_ja) values('0001','架空会社');insert into cases(company_id,title,slug,is_visible) select id,'架空案件','valuation-test',true from companies where security_code='0001';`);
 const policies=(await db.query("select * from pg_policies where tablename like 'user_%' order by tablename,policyname")).rows;
 await db.exec(fs.readFileSync('supabase/migrations/0013_valuation_editions.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/0014_comparable_research.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/0015_long_valuation_forecasts.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/0016_review_research_preservation.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/0017_market_forecast_inputs.sql','utf8'));
 assert.deepEqual((await db.query("select * from pg_policies where tablename like 'user_%' order by tablename,policyname")).rows,policies);
 const session=async(role,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);};
 const save=async(p,revision=null,id='financials:0001')=>(await db.query('select to_jsonb(save_valuation_draft($1,$2,$3)) as r',[id,p,revision])).rows[0].r;
 const publish=async(revision,visible=true,id='financials:0001')=>(await db.query('select to_jsonb(publish_valuation($1,$2,$3)) as r',[id,revision,visible])).rows[0].r;
 const read=async()=>(await db.query('select read_published_valuations() as r')).rows[0].r;
 const [data,peer]=JSON.parse(fs.readFileSync('data/sample/valuations.json','utf8'));
 await session('anon');await assert.rejects(save(data));await assert.rejects(db.query('select * from valuation_editions'));await assert.rejects(read());
 await session('authenticated',other);await assert.rejects(save(data),/管理者/);assert.equal((await db.query('select * from valuation_editions')).rows.length,0);
 await session('authenticated',admin);let row=await save(data);await assert.rejects(db.query('update valuation_editions set published=draft'));
 await session('service_role');assert.deepEqual(await read(),[]);
 await session('authenticated',admin);row=await publish(row.revision);await assert.rejects(save(data,row.revision-1),/競合/);await assert.rejects(publish(null),/競合/);
 const changed=structuredClone(data);changed.facts.eps.value=200;row=await save(changed,row.revision);
 await session('service_role');assert.equal((await read())[0].content.facts.eps.value,100);
 await session('authenticated',admin);row=await publish(row.revision);let peerRow=await save(peer,null,'tob:sample');await publish(peerRow.revision,true,'tob:sample');
 await session('service_role');assert.equal((await read())[0].content.facts.eps.value,200);
 await session('postgres');await db.exec('update cases set is_visible=false');await session('service_role');assert.equal((await read()).length,1);assert.equal((await read())[0].content.kind,'comparable');
 await session('authenticated',admin);row=await publish(row.revision,false);await publish(peerRow.revision+1,false,'tob:sample');
 await session('postgres');await db.exec('update cases set is_visible=true');await session('authenticated',admin);
 const forecastData=structuredClone(data);forecastData.forecastFacts=structuredClone(data.facts);forecastData.forecastFacts.eps.basis='company_forecast';forecastData.forecastFacts.ebitda.basis='company_forecast';
 row=await save(forecastData,row.revision);assert.deepEqual(row.draft.forecastFacts,forecastData.forecastFacts);
 row=await publish(row.revision);await session('service_role');assert.deepEqual((await read())[0].content.forecastFacts,forecastData.forecastFacts);await session('authenticated',admin);row=await publish(row.revision,false);
 for(const forecasts of [null,{}, {cash:data.facts.cash}, {...forecastData.forecastFacts,eps:data.facts.eps}, {...forecastData.forecastFacts,cash:{...data.facts.cash,basis:'company_forecast'}}, {...forecastData.forecastFacts,eps:{...forecastData.forecastFacts.eps,sourceUrl:'https://example.com/?api_key=secret'}}])await assert.rejects(save({...data,forecastFacts:forecasts},row.revision));
 await assert.rejects(save({...peer,forecastFacts:forecastData.forecastFacts},null,'tob:forecast-invalid'));
 for(const bad of [{...data,checkedOn:'2026-02-30'},{...data,facts:{}},{...data,facts:{eps:{...data.facts.eps,value:null}}},{...data,facts:{eps:{...data.facts.eps,sourceUrl:'javascript:alert(1)'}}}])await assert.rejects(save(bad,row.revision));
 const batchSave=async items=>(await db.query('select save_valuation_batch($1) as r',[items])).rows[0].r;
 const batchPublish=async items=>(await db.query('select publish_valuation_batch($1,true) as r',[items])).rows[0].r;
 const researched={...peer,multiples:{},research:{dealId:peer.code+'-20230101',buyer:'架空買付者',transactionType:'mbo',status:'announced',priceBasis:'initial',scope:'consolidated',statisticsEligible:false,definitions:{},denominators:{},valuations:[{advisor:'架空証券',role:'対象会社',date:'2023-01-01',method:'dcf',low:1000,high:1500,page:'10頁',sourceUrl:'https://example.com/valuation.pdf',inputs:[{name:'割引率',unit:'%',period:'算定時点',basis:'valuation_assumption',low:5,high:6,definition:'テスト前提'}],peers:[],notes:'架空テスト'}]}};
 const before=(await db.query('select count(*) as n from valuation_editions')).rows[0].n;
 await assert.rejects(batchSave([{id:'tob:batch-good',payload:researched,revision:null},{id:'tob:batch-bad',payload:{...researched,checkedOn:'2026-02-30'},revision:null}]));
 assert.equal((await db.query('select count(*) as n from valuation_editions')).rows[0].n,before);
 const saved=await batchSave([{id:'tob:batch-a',payload:researched,revision:null},{id:'tob:batch-b',payload:researched,revision:null}]);assert.equal(saved.length,2);
 await assert.rejects(batchPublish([{id:'tob:batch-a',revision:1},{id:'tob:batch-b',revision:99}]),/競合/);
 assert.equal((await db.query("select count(*) as n from valuation_editions where id like 'tob:batch-%' and published is not null")).rows[0].n,0);
 await batchPublish(saved.map(r=>({id:r.id,revision:r.revision})));
 assert.equal((await db.query("select count(*) as n from valuation_editions where id like 'tob:batch-%' and published is not null")).rows[0].n,2);
 // A 20-period DCF has 80 annual figures plus valuation assumptions.
 const long=structuredClone(researched);long.research.valuations[0].inputs=Array.from({length:120},(_,j)=>({...researched.research.valuations[0].inputs[0],name:`前提${j+1}`}));
 const longSaved=await batchSave([{id:'tob:long-forecast',payload:long,revision:null}]);
 assert.deepEqual(longSaved[0].draft.research.valuations[0].inputs,long.research.valuations[0].inputs);
 assert.equal(longSaved[0].published,null);
 const tooLong=structuredClone(long);tooLong.research.valuations[0].inputs.push(tooLong.research.valuations[0].inputs[0]);
 await assert.rejects(batchSave([{id:'tob:long-overflow',payload:tooLong,revision:null}]));
 const unsafeLong=structuredClone(long);unsafeLong.research.valuations[0].inputs[119].high=4;
 await assert.rejects(batchSave([{id:'tob:long-invalid',payload:unsafeLong,revision:null}]));
 const tooManyPeers=structuredClone(long);tooManyPeers.research.valuations[0].peers=Array(61).fill('架空比較会社');
 await assert.rejects(save(tooManyPeers,null,'tob:peers-overflow'));
 const review=structuredClone(researched);review.priceUnit='円/口';review.research.scope='unknown';review.research.valuations[0].date='';review.research.valuations[0].unit='円/口';review.research.valuations[0].methodName='DDM法';
 review.research.sourceReview={packageId:'test-review-v1',sha256:'a'.repeat(64),caseData:{security_code:peer.code,statisticsEligible:false,missing:null,originalNotes:'原典の矛盾を保持',largeContext:'x'.repeat(110000)}};
 const reviewSaved=await batchSave([{id:'tob:raw-review',payload:review,revision:null}]);assert.deepEqual(reviewSaved[0].draft,review);
 await batchPublish(reviewSaved.map(r=>({id:r.id,revision:r.revision})));await session('service_role');assert.deepEqual((await read()).find(r=>r.id==='tob:raw-review').content,review);await session('authenticated',admin);await publish(2,false,'tob:raw-review');
 const ranges=structuredClone(review);ranges.research.valuations=Array.from({length:60},()=>structuredClone(review.research.valuations[0]));assert.equal((await batchSave([{id:'tob:many-ranges',payload:ranges,revision:null}]))[0].draft.research.valuations.length,60);ranges.research.valuations.push(structuredClone(review.research.valuations[0]));await assert.rejects(batchSave([{id:'tob:range-overflow',payload:ranges,revision:null}]));
 for(const change of [r=>r.research.sourceReview.packageId=123,r=>r.research.sourceReview.sha256=123,r=>r.research.statisticsEligible=true,r=>r.research.sourceReview.caseData.security_code='9999',r=>r.research.sourceReview.caseData.statisticsEligible=true,r=>r.research.sourceReview.caseData.largeContext='x'.repeat(200001),r=>r.research.valuations[0].date='2026-02-30',r=>r.priceUnit='USD']){const bad=structuredClone(review);change(bad);await assert.rejects(batchSave([{id:'tob:bad-review',payload:bad,revision:null}]));}
 const broken=structuredClone(researched);broken.research.valuations[0].inputs[0].high=4;await assert.rejects(save(broken,null,'tob:invalid-input'));
 await session('authenticated',other);await assert.rejects(batchSave([{id:'tob:no-admin',payload:researched,revision:null}]),/管理者/);
 await session('authenticated',admin);await publish(2,false,'tob:batch-a');await publish(2,false,'tob:batch-b');
 await session('service_role');assert.deepEqual(await read(),[]);
 await session('authenticated',admin);

 await session('service_role');assert.deepEqual(await read(),[]);
 }finally{await db.close();}
});
